# Generated by Django 4.1.1 on 2022-10-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betreiber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benutzerkonto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
